# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='RegisterAs',
            new_name='Register_As',
        ),
    ]
