# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 12:41
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(default='No description', max_length=1000)),
                ('place', models.CharField(default='Raipur', max_length=50)),
                ('contact', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone Number must be 9 to 12 digits', regex='^\\+?1?\\d{9,12}$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
