# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ngo', '0002_auto_20180220_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='users',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
