# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ngo', '0003_event_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='users',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
